databaseChangeLog:
  - preConditions:
    - runningAs:
        username: hms_user
  - changeSet:
      id: empty-db-hms
      author: mpetric
      changes:
        tag:
          - empty-db-hms
  - changeSet:
      id: create-employees-table
      author: mpetric
      preConditions:
        onFail: MARK_RAN
        onFailMessage: "Table employees already exists"
        not:
          tableExists:
            tableName: employees
      changes:
        - tag:
            - create-hms-table
        - createTable:
            tableName: employees
            columns:
              - column:
                  name: personal_id
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
              - column:
                  name: name
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: team
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: team_lead
                  type: varchar(100)
                  constraints:
                    nullable: false



